# Generated by Django 4.2.4 on 2023-08-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrition',
            new_name='description',
        ),
    ]
